services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'
            $rsceBackendInfoImageMarkup: '%markocupic_contao_rsce_backend_info_image.image_markup%'
            $addAfterRegexPattern: '%markocupic_contao_rsce_backend_info_image.add_after_regex_pattern%'
            $imageSize: '%markocupic_contao_rsce_backend_info_image.image_size%'
            $contaoImageFactory: '@contao.image.factory'

    Markocupic\ContaoRsceBackendInfoImage\:
        resource: ../../
        exclude: ../../{DependencyInjection,Resources,Model}
